# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6ae28d5c94f20fef0c4e91f38ce631a2cabe753be72cf01371d1286cce665ee6a37bc8c30550db4d867db1afcdf09276927ea4c6701ad5d9921ebab982835131

test:
  secret_key_base: 49af51a4878eaaa3e8938d75374eef53d830ee5cbf83b943d791342f1373740d2d817abeb716d8865a36d0817c5a805656c73cea88b97bc99632d28e89727d47

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
